import { CompanySettings } from "../../models/CompanySettings.js";
import logger from "../../config/logger.js";
import {
  IBankAccountInfo,
  AccountingMethod,
} from "../../shared/interface/ICompanySettings.js";

/**
 * Company Settings Service
 * Handles all business logic for company settings
 */
export const companySettingsService = {
  sanitizeBankAccountPayload<T extends Partial<IBankAccountInfo>>(
    bankAccountData: T,
  ): T {
    const payload = { ...bankAccountData } as T;
    const linkedAccountId = (payload as { linkedAccountId?: unknown })
      .linkedAccountId;

    if (linkedAccountId === "") {
      delete (payload as { linkedAccountId?: unknown }).linkedAccountId;
    }

    return payload;
  },

  /**
   * Get company settings
   */
  async getCompanySettings(companyId: string) {
    try {
      let settings = await CompanySettings.findOne({ companyId });

      // Create default settings if they don't exist
      if (!settings) {
        settings = new CompanySettings({
          companyId,
          general: {
            dateFormat: "MM/DD/YYYY",
            timeZone: "Asia/Manila",
            language: "en",
          },
          accounting: {
            accountingMethod: AccountingMethod.ACCRUAL,
            fiscalYearEnd: "12-31",
            baseCurrency: "PHP",
            decimalPlaces: 2,
          },
          invoicing: {
            invoicePrefix: "INV",
            invoiceStartNumber: 1,
            nextSequenceNumber: 1,
            defaultPaymentTerms: "Net 30",
            defaultTaxRate: 12,
            showCompanyLogo: true,
          },
          billing: {
            billPrefix: "BILL",
            billStartNumber: 1,
            nextSequenceNumber: 1,
          },
          payment: {
            paymentPrefix: "PAY",
            paymentStartNumber: 1,
            nextSequenceNumber: 1,
          },
          reporting: {
            reportHeaderText: "Company Financial Report",
            showLogo: true,
            includeFooter: true,
            footerText: "Generated by RRD10 Accounting System",
          },
          notifications: {
            emailNotifications: true,
            reminderDays: [7, 3, 1],
            overdueNotifications: true,
          },
          banking: {
            accounts: [],
          },
        });

        await settings.save();
      }

      return settings;
    } catch (error) {
      logger.logError(error as Error, { operation: "getCompanySettings" });
      throw error;
    }
  },

  /**
   * Update general settings
   */
  async updateGeneralSettings(companyId: string, generalData: any) {
    try {
      const settings = await CompanySettings.findOne({ companyId });

      if (!settings) {
        throw new Error("Company settings not found");
      }

      await settings.updateGeneralSettings(generalData);

      return settings;
    } catch (error) {
      logger.logError(error as Error, { operation: "updateGeneralSettings" });
      throw error;
    }
  },

  /**
   * Add bank account
   */
  async addBankAccount(companyId: string, bankAccountData: IBankAccountInfo) {
    try {
      const settings = await CompanySettings.findOne({ companyId });

      if (!settings) {
        throw new Error("Company settings not found");
      }

      const sanitizedData = this.sanitizeBankAccountPayload(bankAccountData);
      await settings.addBankAccount(sanitizedData);

      return settings;
    } catch (error) {
      logger.logError(error as Error, { operation: "addBankAccount" });
      throw error;
    }
  },

  /**
   * Update bank account
   */
  async updateBankAccount(
    companyId: string,
    bankAccountId: string,
    bankAccountData: Partial<IBankAccountInfo>,
  ) {
    try {
      const settings = await CompanySettings.findOne({ companyId });

      if (!settings) {
        throw new Error("Company settings not found");
      }

      const sanitizedData = this.sanitizeBankAccountPayload(bankAccountData);
      await settings.updateBankAccount(bankAccountId, sanitizedData);

      return settings;
    } catch (error) {
      logger.logError(error as Error, { operation: "updateBankAccount" });
      throw error;
    }
  },

  /**
   * Remove bank account
   */
  async removeBankAccount(companyId: string, bankAccountId: string) {
    try {
      const settings = await CompanySettings.findOne({ companyId });

      if (!settings) {
        throw new Error("Company settings not found");
      }

      await settings.removeBankAccount(bankAccountId);

      return settings;
    } catch (error) {
      logger.logError(error as Error, { operation: "removeBankAccount" });
      throw error;
    }
  },

  /**
   * Get specific bank account
   */
  async getBankAccount(companyId: string, bankAccountId: string) {
    try {
      const settings = await CompanySettings.findOne({ companyId });

      if (!settings) {
        throw new Error("Company settings not found");
      }

      const bankAccount = settings.getBankAccount(bankAccountId);

      if (!bankAccount) {
        throw new Error("Bank account not found");
      }

      return bankAccount;
    } catch (error) {
      logger.logError(error as Error, { operation: "getBankAccount" });
      throw error;
    }
  },
};

export default companySettingsService;
